// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class cambios_de_campos_tabla_cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambios_de_campos_tabla_cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202603200132045_cambios_de_campos_tabla_cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
