// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class crear_tabla_TipoCuenta_y_Cuenta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crear_tabla_TipoCuenta_y_Cuenta));
        
        string IMigrationMetadata.Id
        {
            get { return "202603200137460_crear_tabla_TipoCuenta_y_Cuenta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
